Settings:
  Debug: true #Debug模式，没事别打开..
  Color: true #请务必开启，只对名字有颜色的怪物产生效果
  ScopeDetectTime: 1 #检测附近敌人的间隔时间(整数，秒，若服务器比较卡，建议调大一点)
  AttackCreative: false #是否会攻击创造模式的玩家
AITable: #管理AI模块
  MrHarry: #AI模板名称
    ###########怪物基础设置################
    name: 'Grand Monster' #绑定怪物的名字
    speed: 1.5 #移动速度
    ###########AI基础设置########################
    scope: 30 #觉察到敌人(玩家)的范围(不管看没看到)这里填写20即 20 * 20 * 20的范围 加上这个，你的怪物会更智能
              #这个AI的优先级最高 (0)
    BreakDoor: -1 #会不会拆门 后面加一个优先度 -1表示不设置
    OpenDoor: 1 #会不会开门 -1表示不设置
    Float: 10 #在水里会浮起来吗? (这是不一定的，这里填一个优先级)
    ##########AI事件设置############
    alive: #当怪物活着的时候，增加什么AI
      - Jump #增加跳跃AI
      - 这里还可以输入别的AI
      - 还可以输入别的动作等等
MoveMent: #AI动作
  Jump: #动作名
    random: 5 #AI优先级 (数字越小优先级越大)
    action: jump ~ 0.5 #动作类型和动作参数 这里的0.5是跳跃的范围 负数即为向后跳
